In [ ]:
## Iris dataset — First Application (Chapter 1)

- **Goal:** build a simple supervised learning model to predict the **species** of an iris flower.
- **Features (X):** numeric measurements in centimeters:
  - sepal length, sepal width, petal length, petal width
- **Target (y):** the species (**label**): `setosa`, `versicolor`, `virginica`
- **Problem type:** 3-class **classification**.
- **Why this dataset?** Small, clean, and well-known; great for first experiments.

> Reference: *Introduction to Machine Learning with Python* (Müller & Guido), O’Reilly.


In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display
from sklearn.datasets import load_iris
iris_dataset = load_iris()

print("Keys of iris_dataset:\n", iris_dataset.keys())

Keys of iris_dataset:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [23]:
# Seeing data
print(iris_dataset["DESCR"][:193] + "\n...")
print("\nTarget names:", iris_dataset["target_names"])
print("\nType of data:", type(iris_dataset["data"]))
print("\nShape of data:", iris_dataset["data"].shape)
print("\nType of target:", type(iris_dataset["target"]))
print("\nShape of target:", iris_dataset["target"].shape)
print("\nFirst 5 rows of data:\n", iris_dataset["data"][:5])
print("\nTarget:\n", iris_dataset["target"])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...

Target names: ['setosa' 'versicolor' 'virginica']

Type of data: <class 'numpy.ndarray'>

Shape of data: (150, 4)

Type of target: <class 'numpy.ndarray'>

Shape of target: (150,)

First 5 rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
